n,y,n,y,y,y,n,n,n,y,n,y,y,y,n,y,republican.
n,u,n,y,y,y,n,n,n,n,n,y,y,y,n,y,republican.
n,y,n,y,y,y,n,n,n,y,n,y,y,y,n,n,republican.
n,y,n,y,y,y,n,n,n,y,n,y,y,y,n,y,republican.
n,u,n,y,y,y,n,n,n,n,n,y,y,y,n,n,republican.
n,n,n,y,y,y,n,n,n,n,n,y,y,y,n,y,republican.
y,y,y,n,n,n,y,y,y,n,u,n,n,n,n,u,democrat.
y,n,y,y,y,y,y,y,n,y,y,y,n,y,y,y,republican.
y,n,y,n,n,n,y,y,y,n,n,n,n,n,y,u,democrat.
n,y,y,n,u,y,n,n,n,n,y,n,y,n,n,y,democrat.
n,y,n,y,y,y,n,n,n,y,n,y,y,y,n,y,republican.
n,n,u,n,n,y,y,y,y,n,n,n,n,n,y,y,democrat.
n,n,y,n,n,y,y,y,y,n,n,n,n,n,y,y,democrat.
y,n,y,n,n,n,y,y,y,n,n,n,n,n,n,y,democrat.
n,u,n,y,y,y,n,n,n,n,y,y,y,y,n,y,republican.
y,n,n,n,n,n,y,y,y,y,n,n,n,y,n,y,republican.
n,n,n,y,y,y,n,n,n,y,n,y,y,y,n,n,republican.
n,y,y,n,n,y,n,y,y,n,y,n,y,n,y,y,democrat.
y,y,y,n,u,y,y,y,n,y,u,u,n,n,y,y,democrat.
y,y,y,n,n,n,y,y,y,y,y,n,y,n,n,y,democrat.
n,n,y,n,n,n,y,y,y,n,n,n,n,n,y,y,democrat.
n,n,n,y,y,y,n,n,n,n,n,y,y,y,n,n,republican.
y,u,y,n,n,n,y,y,y,n,n,n,y,n,y,y,democrat.
n,n,n,y,y,y,n,n,n,y,y,y,n,y,n,y,republican.
n,n,y,n,n,n,y,y,y,y,y,n,n,n,y,y,democrat.
n,y,n,y,y,y,n,n,n,y,u,y,y,y,n,y,republican.
y,n,n,n,n,n,y,y,y,y,n,n,n,n,y,y,democrat.
n,n,y,n,n,y,u,y,u,y,y,y,n,y,y,u,democrat.
y,n,y,n,n,n,y,y,y,n,y,n,n,n,y,u,democrat.
y,n,y,n,n,n,y,y,y,n,y,n,n,n,y,y,democrat.
n,n,n,y,y,n,n,n,n,y,n,y,y,y,n,n,republican.
y,u,y,n,n,n,y,y,y,n,n,n,n,n,y,u,democrat.
n,n,n,n,n,y,y,y,y,n,y,n,n,y,y,y,democrat.
n,n,n,y,y,y,y,n,n,y,n,y,n,y,y,y,republican.
y,y,y,n,y,y,n,n,u,y,n,n,n,y,y,u,democrat.
n,u,y,u,n,y,y,y,y,y,y,n,u,u,y,y,democrat.
n,n,y,n,n,y,y,y,y,y,y,n,y,y,n,y,democrat.
y,n,y,n,n,n,y,y,y,n,n,n,n,n,y,y,democrat.
y,n,y,n,n,n,y,y,y,y,n,n,n,n,n,y,democrat.
y,n,y,n,n,n,y,y,y,n,n,n,n,n,y,u,democrat.
y,y,y,n,n,n,y,y,y,y,n,n,y,n,y,y,democrat.
y,y,y,y,y,y,n,n,n,n,y,y,y,y,n,y,democrat.
y,n,y,n,y,y,y,n,n,n,y,n,n,y,n,y,democrat.
y,n,y,n,n,n,y,y,y,n,n,n,y,n,y,u,democrat.
n,n,y,n,n,n,y,y,y,y,y,n,u,n,y,u,democrat.
y,n,y,n,y,y,n,n,y,y,n,n,y,y,n,y,democrat.
n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,n,republican.
n,y,n,y,y,y,n,n,y,y,n,y,y,y,n,y,republican.
y,y,y,n,n,n,y,y,y,n,n,n,n,n,n,u,democrat.
y,n,n,y,y,n,y,y,y,n,n,y,y,y,n,y,republican.
n,y,y,y,y,y,n,y,y,y,y,y,y,y,n,y,democrat.
n,y,n,y,y,y,n,n,n,y,y,y,y,y,n,y,republican.
n,y,n,n,y,y,n,n,n,n,n,y,y,y,y,y,democrat.
n,y,n,n,n,y,y,n,y,n,y,n,n,n,y,y,democrat.
n,y,y,y,y,y,y,n,y,y,n,y,y,y,n,y,republican.
n,n,n,y,y,y,n,n,n,y,n,y,n,y,n,y,republican.
y,n,y,n,n,n,y,y,y,y,n,u,n,n,y,y,democrat.
n,n,y,n,n,y,n,y,y,y,n,n,n,y,n,y,democrat.
n,u,u,y,y,y,n,n,n,y,n,y,y,y,u,y,republican.
n,n,n,y,y,y,n,n,n,y,n,y,y,y,n,n,republican.
n,y,n,y,y,n,n,n,n,n,u,u,y,y,n,n,republican.
n,n,y,n,n,y,y,y,y,n,y,y,n,y,y,u,democrat.
n,n,n,y,y,n,n,n,n,n,n,y,n,y,u,y,republican.
n,y,n,y,y,y,n,u,n,n,u,u,u,y,n,u,republican.
n,n,n,y,y,y,n,n,n,n,n,y,y,y,n,n,republican.
n,n,y,n,n,y,y,y,y,y,n,n,n,y,n,y,democrat.
y,n,y,n,n,n,u,y,y,u,n,n,n,n,y,u,democrat.
y,n,y,n,n,y,y,y,y,n,n,n,n,y,n,u,democrat.
y,n,n,n,y,y,u,n,u,n,n,n,n,y,u,n,democrat.
n,n,y,n,n,y,y,y,y,y,y,n,n,n,u,y,democrat.
n,y,n,y,y,y,n,n,n,y,n,y,y,y,u,n,republican.
n,y,n,y,y,y,n,n,n,y,n,y,y,y,n,u,republican.
y,n,y,y,n,n,n,y,y,y,n,n,n,y,y,y,republican.
n,y,y,y,y,y,y,y,y,n,n,y,y,y,n,y,republican.
y,n,y,n,y,y,y,n,u,n,y,n,y,y,y,u,democrat.
y,n,y,n,n,n,y,y,y,n,y,n,n,n,y,y,democrat.
y,n,y,n,n,n,y,y,y,y,n,n,n,y,y,y,democrat.
y,y,y,n,n,u,y,y,y,y,n,n,n,n,y,u,democrat.
y,n,y,n,n,u,y,y,y,n,u,u,n,u,u,u,democrat.
n,y,n,y,y,y,y,y,n,n,y,y,y,y,y,y,republican.
n,n,n,y,y,y,n,n,n,y,n,y,y,y,n,n,republican.
y,y,y,n,n,n,y,y,y,n,n,n,n,n,u,u,democrat.
n,n,n,y,y,n,n,n,n,n,n,y,n,y,n,n,republican.
y,u,y,n,n,n,y,y,y,n,n,n,y,n,y,y,democrat.
y,n,y,n,n,n,y,y,y,n,n,n,n,n,n,y,democrat.
y,y,n,y,y,y,n,n,n,y,n,y,y,y,n,n,republican.
n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,y,republican.
n,n,n,y,y,y,n,n,n,n,n,y,y,y,n,n,republican.
n,y,y,y,y,y,n,n,n,n,y,y,u,y,n,n,democrat.
n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,y,republican.
y,y,y,n,n,n,y,y,y,n,y,n,n,n,n,y,democrat.
y,n,n,y,y,y,n,n,n,y,n,y,y,y,n,n,republican.
y,n,y,n,n,n,y,y,y,y,y,n,n,n,y,y,democrat.
y,y,y,n,n,n,y,y,y,n,y,n,n,n,y,u,democrat.
n,y,y,n,n,y,y,y,n,y,n,n,n,n,y,y,democrat.
n,n,u,n,y,y,n,n,n,n,y,y,y,y,n,y,democrat.
u,y,n,n,n,n,y,y,y,y,y,n,n,y,y,y,democrat.
n,n,y,n,n,n,y,y,y,n,y,n,n,n,y,y,democrat.
u,u,y,n,n,n,y,y,y,u,u,n,n,n,u,u,democrat.
y,y,y,n,n,n,y,y,y,n,n,n,n,n,y,u,democrat.
y,n,y,n,n,n,y,y,y,y,n,n,n,y,y,y,democrat.
y,y,y,n,n,n,y,y,n,y,y,n,n,u,y,y,democrat.
y,y,y,n,n,n,y,y,n,y,n,n,n,n,n,y,democrat.
y,y,y,n,n,y,y,y,y,y,n,n,u,n,y,u,democrat.
y,y,y,n,u,y,n,u,n,n,y,n,y,y,n,u,democrat.
n,n,y,n,n,y,y,u,y,y,y,n,n,n,y,y,democrat.
y,n,n,y,y,y,n,n,n,y,n,u,y,y,n,n,republican.
y,y,y,n,n,n,y,y,y,n,y,n,n,n,n,y,democrat.
y,y,n,y,y,y,n,n,n,y,y,n,y,n,n,n,republican.
n,y,y,n,n,y,y,y,y,y,y,n,y,n,y,u,democrat.
y,y,y,n,n,n,y,y,y,n,y,n,n,n,y,y,democrat.
y,u,n,y,y,y,n,n,n,y,n,y,u,y,n,y,republican.
n,n,y,n,n,n,y,y,y,n,n,n,n,n,y,u,democrat.
y,n,y,n,n,n,y,y,y,y,n,n,n,n,n,y,democrat.
n,y,n,y,y,y,n,n,n,y,n,y,y,y,n,n,republican.
u,n,y,y,n,y,y,y,y,y,n,y,n,y,n,y,republican.
y,n,y,n,n,y,y,y,y,y,y,n,n,y,y,y,democrat.
n,n,y,n,y,n,y,y,y,n,n,n,n,y,u,y,democrat.
y,y,y,n,n,n,y,y,y,n,n,n,n,n,y,y,democrat.
n,y,n,y,y,y,y,n,n,n,y,y,y,y,n,y,republican.
n,n,n,y,y,y,u,u,u,u,n,y,y,y,n,y,republican.
n,y,y,n,n,n,y,y,u,y,n,n,y,n,y,y,democrat.
y,u,y,n,n,n,y,y,y,n,n,n,n,n,y,u,democrat.
y,y,y,n,y,y,n,y,n,y,y,n,y,y,n,u,democrat.
n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,y,republican.
n,n,n,y,y,y,n,n,n,y,n,y,n,y,n,y,republican.
y,y,y,n,y,y,y,y,y,y,y,n,y,y,n,u,democrat.
y,y,y,n,n,y,y,y,y,y,y,y,y,y,n,u,democrat.
n,n,n,y,y,y,n,n,n,y,n,y,y,y,n,y,republican.
u,y,y,u,y,y,n,n,n,n,y,n,y,y,n,n,democrat.
n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,n,republican.
n,n,y,n,n,n,y,y,y,n,n,n,n,n,y,y,democrat.
n,y,n,n,y,y,n,n,n,y,y,n,y,y,n,n,democrat.
n,n,n,y,y,y,y,n,n,y,n,n,n,y,y,y,republican.
y,y,n,n,n,n,y,y,u,n,y,n,n,n,y,u,democrat.
